### ISSUE TITLE
What about mutations?

### ISSUE THREAD

**Issue by mathieutu** [b1f6c1c4/graphql-advanced-projection#8]
Hi, I'm using your package and trying to do something cool for mutations too.
Could you provide some examples?

Here an example of nested items, where I want just to add a child and return the parent.

For now, I have:
```js
async addQuestion(root, { campaignId, question }, ctx, info) {
    const campaign = await Campaign.findById(campaignId);
    const lenght = campaign.questions.push(question);
    
    return campaign.save();
}
```

```graphql
mutation($campaignId: ID, $question: QuestionInput) {
  addQuestion(question: $question, campaignId: $campaignId) {
    id
    title
  }
}
```
which is pretty bad because I can't really select any field of the object, and load everything.

If I use the projection in the `findById`, `questions` is undefined.

And if I have a lot of questions in campaign, they will all be loaded (with their own children) for nothing.

Do you have any ideas/tips ?

Thanks!

**Comment by b1f6c1c4** [comment]
(Assuming you're using MongoDB)
@mathieutu  You may use `db.collection.updateOne({ _id: <ID> }, { $push: { questions: <QUESTION> } })` to update the document first; then follow the standard workflow of making queries (including projection).

However, if there to TOO MANY subdocuments in a document, you may (after calling `updateOne`) use aggregation (instead of queries) to retrieve docs. These operators may help:

- [`$arrayElemAt`](https://docs.mongodb.com/manual/reference/operator/aggregation/arrayElemAt/)
- [`$unwind`](https://docs.mongodb.com/manual/reference/operator/aggregation/unwind/) and [`$replaceRoot`](https://docs.mongodb.com/manual/reference/operator/aggregation/replaceRoot/) combo
- [`$redact`](https://docs.mongodb.com/manual/reference/operator/aggregation/redact/)

In the latter case, `graphql-advanced-projection` might still be helpful. On the [`aggregate`](https://github.com/b1f6c1c4/graphql-advanced-projection/blob/aggregate/examples/aggregate/index.js) branch are some relics of my abandoned work aiming to provide a universal framework for automatically creating such aggreagtion. Unfortunately, as mentioned by commit 104c10424dc7a4a189182cfb1fa69102a68d92a0, I seemed totally wrong. Go `aggregate` branch and have a look.

**Comment by mathieutu** [comment]
ok, thanks, I'll look around all of that.

(but I still think that some mutation examples will be welcomed! 😄)
